### ISSUE TITLE
Process for updating the filters?

### ISSUE THREAD

**Issue by kalbasit** [antifuchs/gmail-britta#13]
Hello,

I couldn't find any information on how to update the filters that were previously updated to Gmail. Do you deleted them all and upload the new set or do you simply upload the newly generated set?

/cc @jpiasetz @pathzzrd

**Comment by antifuchs** [comment]
Thanks for asking! Currently the only way to update filters is indeed to delete all existing filters, and to import the new .xml file. 

There is an optimization where if you only added filters, you can skip the deletion step (and in return, if you have any manually-added filters, you have to make sure not to delete those).

I'd love if the gmail API allowed deleting existing filters - at the moment, it only supports adding filters, and that's not enough to sync the existing set up with new filters )-:

I hope this helps!

**Comment by kalbasit** [comment]
That helps, thanks.

**Comment by kalbasit** [comment]
@antifuchs perhaps we could at least have a way to print the added ones only if we can? For now, I'll probably just delete anything I haven't added or edited.
