### ISSUE TITLE
"smart_label method undefined" message

### ISSUE THREAD

**Issue by 573** [antifuchs/gmail-britta#16]
When I run `examples/asf.rb` (`./myfilter.rb`) I get:

>myuser@MACHINE:~/my-mail-filters/dfefe5565260c07f378d master
$ ./myfilter.rb
./myfilter.rb:25:in \`block (2 levels) in \<main>': undefined method \`smart_label' for #\<GmailBritta::Filter:0x000006002f4760> (NoMethodError)
        from /home/myuser/.gem/ruby/2.1.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter.rb:159:in \`instance_eval'
        from /home/myuser/.gem/ruby/2.1.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter.rb:159:in \`perform'
        from /home/myuser/.gem/ruby/2.1.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter_set.rb:63:in \`filter'
        from ./myfilter.rb:22:in \`block in \<main>'
        from /home/myuser/.gem/ruby/2.1.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter_set.rb:71:in \`instance_eval'
        from /home/myuser/.gem/ruby/2.1.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter_set.rb:71:in \`perform'
        from /home/myuser/.gem/ruby/2.1.0/gems/gmail-britta-0.1.6/lib/gmail-britta/filter_set.rb:28:in \`rules'
        from /home/myuser/.gem/ruby/2.1.0/gems/gmail-britta-0.1.6/lib/gmail-britta.rb:29:in \`filterset'
        from ./myfilter.rb:20:in \`\<main>'

**Comment by antifuchs** [comment]
Eep, that sounds weird. I can't reproduce this on latest master; what's the exact version of gmail-britta you're on?

Speaking of, I should cut a new release with all these changes. I'll update here when the new release is out.

**Comment by antifuchs** [comment]
I pushed a new release, 0.1.7, to rubygems.org now. I'd really appreciate if you could try with that version! (-:

**Comment by 573** [comment]
Hi sorry for being so late I was in vacations and barely had a computer at hand: Good news is I confirm version 0.1.7 to work with the smart labels now! Thanks for this great software!

**Comment by antifuchs** [comment]
Excellent, glad it works! (:
