### ISSUE TITLE
archive_unless_directed and labels?

### ISSUE THREAD

**Issue by aspiers** [antifuchs/gmail-britta#20]
Hi there, thanks a lot for sharing this cool utility!

The README claims that

```ruby
GmailBritta.filterset do
  filter {
    has %w{list:discuss@lists.some-side-project.org}
  }.archive_unless_directed
end
```

is equivalent to

```
list:discuss@lists.some-side-project.org !to:thisisme@mydomain.com
     -> Archive
list:discuss@lists.some-side-project.org
     -> Label "some-side-project"
```

but the latter references the `some-side-project` label whereas the former doesn't.  Does `archive_unless_directed` have some undocumented label inference magic, or is the README wrong?

**Comment by antifuchs** [comment]
That was totally an error in the README; sorry about that & thanks for spotting it!
