### ISSUE TITLE
Allow multiple labels

### ISSUE THREAD

**Issue by lekv** [antifuchs/gmail-britta#24]
Sometimes I find that I want multiple labels attached through the same filter. GMail doesn't support that, but we could issue the same filter repeatedly for each label.

**Comment by antifuchs** [comment]
I have now made #27 to support better filter chaining. Feel free to test that branch out - I'll leave the PR open for a while and cut a new release if it doesn't break for you (:

**Comment by antifuchs** [comment]
#27 is merged now - I'd still love to hear any feedback you have on it (:

**Comment by lekv** [comment]
Apologies for the late reply. I'll check out the new branch and `.also` and will report any issues.

**Comment by lekv** [comment]
I tried the recent HEAD and the generated filters are the same as the previous version I had used (736078d).
