### ISSUE TITLE
:or entries with spaces are not grouped

### ISSUE THREAD

**Issue by FiloSottile** [antifuchs/gmail-britta#25]
I would expect the following filter to include an email with "aaa ccc" in the body.

```ruby
    filter {
      has [{:or => [
        'aaa', 'bbb -ccc',
      ]}]
      archive_unless_directed
    }
```

Instead, it generates `(aaa OR bbb -ccc)` which is different from the expected `(aaa OR (bbb -ccc))`.

**Comment by antifuchs** [comment]
What a tasty bug! Thanks for reporting, I have pushed what I think is a fix (and a regression test) (:
