### ISSUE TITLE
How gamil-britta solves that XML filter list may be randomly reordered on import?

### ISSUE THREAD

**Issue by matkoniecz** [antifuchs/gmail-britta#28]
> What this library does is generate XML that you can import.

Is this XML file resistant to fact that Gmail recently [to randomly reorder files imported from XML](https://webapps.stackexchange.com/questions/121474/why-import-of-my-gmail-filters-is-silently-failing)? It broke my homegrown filter generator that also had chaining support and I am curious is britta solution for my problem or is it also affected.

**Comment by antifuchs** [comment]
Huh, that's concerning. I haven't seen import failures yet (on my 500 filter setup), but if they start randomly reordering filters, the XML that gmail-britta generates is likely just as affected as your tool.

One thing that might work is to use the new [`users.settings`](https://developers.google.com/gmail/api/v1/reference/users/settings/filters) api that gmail offers; I believe [gmail-yaml-filters](https://github.com/mesozoic/gmail-yaml-filters) can be configured to use that. 

I'll close this issue, but feel free to comment with your experience reports here!

**Comment by matkoniecz** [comment]
Thanks for the reply! 

Huh. So either I am really unlucky or something weird is happening. Or maybe it affects overgrown filter lists, mine had 1800 filters when I noticed it and I reduced it to 800.

I will try to review filters and go to 500, maybe it will fix my problem.

**Comment by bexelbie** [comment]
As another data point, and not intending to reopen - I am seeing reordering on a 28 rule filter.
